version: '2'
services:
  test:
    build: .
    tty: true
    user: "${UID}"
    volumes:
      - .:/v
    working_dir: /v
    environment:
      PG_URL: 'postgres://postgres:pon@pg:5432/postgres'
      MYSQL_URL: 'mysql://user:pass@mysql:3306/test'
      SQLITE_URL: 'sqlite3:/tmp/test.db'
    depends_on:
      - pg
      - mysql
  pg:
    image: postgres:12.4
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pon
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
